//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductList
    {
        public int PK_ImageId { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public string Location { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> SaveRate { get; set; }
        public Nullable<double> OfferRate { get; set; }
        public Nullable<int> Position { get; set; }
        public string ImageHeading { get; set; }
        public string Category { get; set; }
        public Nullable<bool> IsCOD { get; set; }
        public Nullable<bool> IsFreeDel { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> ShowTop_3 { get; set; }
        public Nullable<bool> ShowMid_3 { get; set; }
        public Nullable<bool> ShowBottom_3 { get; set; }
        public Nullable<bool> ShowSlider10 { get; set; }
        public Nullable<bool> ShowLeft_5 { get; set; }
        public Nullable<int> ShowSingle_1 { get; set; }
    }
}
